title: Andrew Williamson
description: Senior Machine Learning Engineer
baseurl: ""
url: "https://awilliamson10.github.io"

# Social links
github_username: awilliamson10
twitter_username: ""
rss: true

# Plugins
plugins:
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

